import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'it';

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    // Header
    'header.favorites': 'Favorites',
    'header.signOut': 'Sign Out',
    'header.signIn': 'Sign In',
    'header.postListing': 'Post Listing',
    'header.getStarted': 'Get Started',
    'header.publishListings': 'Publish Listings',
    'header.myListings': 'My Listings',
    'header.messages': 'Messages',
    'header.about': 'About Us',
    'header.profile': 'Profile',
    'header.profileInfo': 'Profile Information',
    'header.language': 'Language',
    'header.hello': 'Hello',
    'header.logIn': 'Log In',
    'header.start': 'Start',
    'header.account': 'Account',
    'header.landlord': "I'm a landlord",
    
    // Languages
    'language.english': 'English',
    'language.italian': 'Italian',
    
    // About Page
    'about.title': 'About Us',
    'about.backHome': 'Back Home',
    'about.intro1': 'Tired of the low quality of real estate services in Milan, we decided to build a platform to make it safer and easier for students who move to University to find a place to live.',
    'about.intro2': 'We carefully select the real estate companies and landowners who share their announcements on this platform based on various criteria–quality-price ratio, responsiveness, comfort–in order to reduce the stress of students as much as possible. We also make sure that only students can make purchases on this platform in order to protect landowners. Enjoy the website and good luck finding your perfect home!',
    'about.founders': 'Melchior and Teo',
    'about.contactInfo': 'Contact Information',
    'about.email': 'Email:',
    'about.partnerTitle': 'Want to partner with us?',
    'about.partnerText': 'Write at',
    'about.partnerOr': 'or schedule a meeting right now',
    'about.scheduleMeeting': 'Schedule Meeting',
    
    // Homepage
    'home.heroWelcome': 'Welcome back',
    'home.heroTitle': 'Your perfect student home here and now.',
    'home.heroSubtitle': 'Connecting students with verified housing near Bocconi University and other top Milan universities. Trusted by agencies, loved by students.',
    'home.heroSubtitleStudent': 'Ready to find your perfect student accommodation?',
    'home.heroSubtitleRealtor': 'Manage your listings and connect with potential tenants.',
    'home.findPlace': 'Find a Place',
    'home.goToMyListings': 'Go to my Listings',
    'home.universitiesTitle': 'Perfect for students near leading universities.',
    'home.universitiesSubtitle': 'Find housing within walking distance or easy commute to Milan\'s best universities',
    'home.featuredTitle': 'Featured Properties',
    'home.featuredSubtitle': 'Hand-picked accommodations from trusted agencies',
    'home.featured': 'Featured',
    'home.month': '/month',
    'home.viewDetails': 'View Details',
    'home.viewAll': 'View All Properties',
    'home.quickActions': 'Quick Actions',
    'home.quickActionsSubtitle': 'Access your most important features',
    'home.messages': 'Messages',
    'home.messagesDesc': 'Chat with landlords and agencies',
    'home.messagesDescRealtor': 'Chat with potential tenants',
    'home.savedListings': 'Saved Listings',
    'home.savedListingsDesc': 'View your favorite properties',
    'home.explore': 'Explore',
    'home.exploreDesc': 'Discover new properties',
    'home.addListing': 'Add Listing',
    'home.addListingDesc': 'Create a new property listing',
    'home.myListings': 'My Listings',
    'home.myListingsDesc': 'View and manage your properties',
    'home.analytics': 'Analytics',
    'home.analyticsDesc': 'View listing performance',
    'home.recentActivity': 'Recent Activity',
    'home.recentActivityDesc': 'No recent activity yet. Start exploring to see your activity here!',
    'home.dashboardStats': 'Dashboard Stats',
    'home.dashboardStatsDesc': 'Overview of your listing performance',
    'home.activeListings': 'Active Listings',
    'home.totalViews': 'Total Views',
    'home.inquiries': 'Inquiries',
    'home.needHelp': 'Need Help?',
    'home.contactUs': 'Contact us at teodor.cosmovici@studbocconi.it',
    'home.helpDesc': 'We are here to help you with anything you need. We answer in 24 hours or less.',
    'home.quickActionsRealtorSubtitle': 'Manage your property listings and business',
    
    // Benefits Section
    'home.whyChooseTitle': 'Why choose flat2study?',
    'home.whyChooseSubtitle': 'We make finding student accommodation in Milan safe, easy, and reliable.',
    'home.verifiedProperties': 'Verified Properties',
    'home.verifiedPropertiesDesc': 'All properties are verified and listed by trusted agencies and landlords.',
    'home.studentOnly': 'Student-Only',
    'home.studentOnlyDesc': 'Exclusive platform for students, ensuring the best experience for all users.',
    'home.perfectLocations': 'Perfect Locations',
    'home.perfectLocationsDesc': 'Properties near top Milan universities with easy commute options.',
    
    'addYourListings': 'Add Your Listing',
    
    // Auth Page
    'auth.backToHome': 'Back to Home',
    'auth.title': 'Log In to Flat2Study',
    'auth.description': 'Access your account to manage your listings and messages',
    'auth.checkingAuth': 'Checking authentication...',
    'auth.email': 'Email',
    'auth.emailPlaceholder': 'your.email@example.com',
    'auth.password': 'Password',
    'auth.passwordPlaceholder': 'Enter your password',
    'auth.logIn': 'Log In',
    'auth.forgotPassword': 'Forgot your password?',
    'auth.resetTitle': 'Reset your password',
    'auth.resetDescription': 'Enter your email address and we\'ll send you a link to reset your password.',
    'auth.sendResetEmail': 'Send Reset Email',
    'auth.backToLogin': 'Back to log in',
    'auth.noAccount': 'Don\'t have an account?',
    'auth.getStarted': 'Get started here',
    'auth.passwordsNoMatch': 'Passwords do not match',
    'auth.passwordTooShort': 'Password must be at least 6 characters long',
    'auth.accountExists': 'An account with this email already exists. Please log in instead.',
    'auth.createFailed': 'Failed to create account',
    'auth.accountCreated': 'Account created successfully! Please check your email to verify your account.',
    'auth.loginFailed': 'Failed to log in',
    'auth.resetFailed': 'Failed to send reset email',
    'auth.resetSuccess': 'Password reset email sent! Check your inbox and follow the instructions.',
    
    // User Type Selection
    'userType.backToHome': 'Back to Home',
    'userType.title': 'Get Started with Flat2Study',
    'userType.description': 'Choose your profile type to create an account',
    'userType.realtorTitle': 'For real estate agencies',
    'userType.realtorDescription': 'Real estate professionals managing multiple properties',
    'userType.realtorFeatures': 'List and manage properties, connect with potential tenants, track inquiries',
    'userType.privateTitle': 'For private landlords and property managers',
    'userType.privateDescription': 'Individual property owners renting their properties',
    'userType.privateFeatures': 'List and manage properties, connect with potential tenants, track inquiries',
    'userType.studentTitle': 'For Apartment Seekers',
    'userType.studentDescription': 'Students looking for accommodation',
    'userType.studentFeatures': 'Search properties, save favorites, request viewings, connect with landlords',
    'userType.getStarted': 'Get Started',
    'userType.alreadyAccount': 'Already have an account?',
    'userType.logInHere': 'Log in here',
    
    // Signup Student
    'signup.student.backToSelection': 'Back to Selection',
    'signup.student.title': 'Student Registration',
    'signup.student.description': 'Create your account to start searching for accommodations',
    'signup.student.profilePicture': 'Profile Picture',
    'signup.student.uploadPhoto': 'Upload Photo',
    'signup.student.name': 'Name',
    'signup.student.surname': 'Surname',
    'signup.student.namePlaceholder': 'First name',
    'signup.student.surnamePlaceholder': 'Last name',
    'signup.student.phone': 'Phone Number',
    'signup.student.phonePlaceholder': '+39 123 456 7890',
    'signup.student.university': 'University',
    'signup.student.universityPlaceholder': 'Select your university',
    'signup.student.selectUniversity': 'Please select your university',
    'signup.student.email': 'Email',
    'signup.student.passwordCreate': 'Create a password (min. 6 characters)',
    'signup.student.confirmPassword': 'Confirm Password',
    'signup.student.confirmPasswordPlaceholder': 'Confirm your password',
    'signup.student.createAccount': 'Create Student Account',
    'signup.student.alreadyHaveAccount': 'Already have an account?',
    'signup.student.logInHere': 'Log in here',
    
    // Signup Realtor
    'signup.realtor.title': 'Realtor Registration',
    'signup.realtor.description': 'Create your professional account to start listing properties',
    'signup.realtor.emailPlaceholder': 'your.email@company.com',
    'signup.realtor.company': 'Company',
    'signup.realtor.companyPlaceholder': 'Real Estate Agency Name',
    'signup.realtor.license': 'License Number',
    'signup.realtor.licensePlaceholder': 'Professional license number',
    'signup.realtor.createAccount': 'Create Realtor Account',
    
    // Signup Private
    'signup.private.title': 'Landlord and Property Manager Registration',
    'signup.private.description': 'Create your account to start listing your property',
    'signup.private.birthDate': 'Birth Date',
    'signup.private.codiceFiscale': 'Codice Fiscale',
    'signup.private.codiceFiscalePlaceholder': 'RSSMRA80A01H501Z',
    'signup.private.createAccount': 'Create Account',
    'signup.private.termsAccept': 'I accept the',
    'signup.private.termsOfUse': 'Terms of Use',
    'signup.private.privacyAccept': 'I accept the',
    'signup.private.privacyPolicy': 'Privacy Policy',
    'signup.private.required': '*',
    'signup.private.termsError': 'You must accept the Terms of Use to continue',
    'signup.private.privacyError': 'You must accept the Privacy Policy to continue',
    
    // Universities
    'university.bocconi': 'Bocconi University',
    'university.politecnico': 'Politecnico di Milano',
    'university.cattolica': 'Università Cattolica del Sacro Cuore',
    'university.statale': 'Università Statale',
    'university.other': 'Another University',
    
    // Search Page
    'search.placeholder': 'Search by location, university, or amenities...',
    'search.sortBy': 'Sort by:',
    'search.relevance': 'Relevance',
    'search.priceLowHigh': 'Price: Low to High',
    'search.priceHighLow': 'Price: High to Low',
    'search.newest': 'Newest First',
    'search.distance': 'Distance',
    'search.loading': 'Loading listings...',
    'search.propertiesInView': 'properties in current view',
    'search.noPropertiesView': 'No properties in current view.',
    'search.moveMap': 'Move the map to see listings in different areas',
    'search.noResults': 'No properties match your search criteria.',
    'search.clearFilters': 'Clear Filters',
    
    // Profile Page
    'profile.back': 'Back',
    'profile.about': 'About',
    'profile.agency': 'Agency',
    'profile.student': 'Student',
    'profile.tellAbout': 'Tell us about yourself...',
    'profile.characters': 'characters',
    'profile.cancel': 'Cancel',
    'profile.save': 'Save',
    'profile.saving': 'Saving...',
    'profile.noDescription': 'No description added yet. Click the edit button to add one.',
    'profile.contact': 'Contact',
    'profile.contactInformation': 'Contact Information',
    'profile.memberSince': 'Member since',
    'profile.pleaseSignIn': 'Please sign in to view your profile.',
    
    // Common
    'common.email': 'Email',
    'common.phone': 'Phone',
    'common.address': 'Address',
    'common.city': 'City',
    'common.country': 'Country',
    'common.price': 'Price',
    'common.bedrooms': 'Bedrooms',
    'common.bathrooms': 'Bathrooms',
    'common.furnished': 'Furnished',
    'common.available': 'Available',
    'common.contact': 'Contact',
    'common.viewDetails': 'View Details',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.back': 'Back',
    'common.send': 'Send',
    'common.sending': 'Sending...',
    'common.select': 'Select',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.create': 'Create',
    'common.update': 'Update',
    'common.view': 'View',

    // Landlord Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.addListing': 'Add listing',
    'dashboard.addAListing': 'Add a listing',
    'dashboard.backToHome': 'Back to Home',
    'dashboard.logout': 'Logout',
    'dashboard.listings': 'Listings',
    'dashboard.bookingRequests': 'Booking requests',
    'dashboard.confirmedBookings': 'Confirmed bookings',
    'dashboard.account': 'Account',
    'dashboard.loadingDashboard': 'Loading dashboard...',
    'dashboard.quickFind': 'Quick find',
    'dashboard.addressReference': 'ADDRESS / REFERENCE',
    'dashboard.price': 'PRICE',
    'dashboard.verification': 'VERIFICATION',
    'dashboard.tenantsInterested': 'TENANTS INTERESTED',
    'dashboard.actions': 'ACTIONS',
    'dashboard.bed': 'bed',
    'dashboard.bath': 'bath',
    'dashboard.ref': 'REF',
    'dashboard.bedroom': 'Bedroom',
    'dashboard.requests': 'requests',
    'dashboard.rented': 'Rented',
    'dashboard.published': 'Published',
    'dashboard.rejected': 'Rejected',
    'dashboard.pending': 'Pending',
    'dashboard.deleteListing': 'Delete Listing',
    'dashboard.deleteListingConfirm': 'Are you sure you want to delete this listing? This action cannot be undone.',
    'dashboard.cancel': 'Cancel',
    'dashboard.delete': 'Delete',
    'dashboard.success': 'Success',
    'dashboard.listingDeleted': 'Listing deleted successfully',
    'dashboard.error': 'Error',
    'dashboard.deleteListingError': 'Failed to delete listing',
    'dashboard.listingMarkedRented': 'Listing marked as rented out successfully',
    'dashboard.updateListingError': 'Failed to update listing status',
    'dashboard.noListingsYet': 'No listings yet',
    'dashboard.createFirstListing': 'Create your first listing to start receiving booking requests.',
    'dashboard.getStarted': 'Get Started',
    'dashboard.noBookingRequests': 'No booking requests',
    'dashboard.noBookingRequestsDesc': 'When students request to book your properties, they\'ll appear here.',
    'dashboard.noConfirmedBookings': 'No confirmed bookings',
    'dashboard.noConfirmedBookingsDesc': 'Confirmed bookings will appear here.',
    'dashboard.profileInfo': 'Profile Information',
    'dashboard.editProfile': 'Edit Profile',
    'dashboard.signedInAs': 'You are signed in as',
    'dashboard.checkIn': 'Check-in',
    'dashboard.checkOut': 'Check-out',
    'dashboard.monthlyRent': 'Monthly rent',
    'dashboard.totalAmountRequested': 'Total amount requested',
    'dashboard.tenant': 'Tenant',
    'dashboard.university': 'University',
    'dashboard.createdAt': 'Created at',
    'dashboard.approve': 'Approve',
    'dashboard.decline': 'Decline',
    'dashboard.bookingApproved': 'Booking request approved successfully',
    'dashboard.bookingDeclined': 'Booking request declined successfully',
    'dashboard.bookingUpdateError': 'Failed to update booking request',
    'dashboard.noListingsEmpty': 'No listings yet',
    'dashboard.createFirstListingDesc': 'Create your first property listing to start attracting tenants.',
    'dashboard.createYourFirstListing': 'Create Your First Listing',
    'dashboard.noBookingRequestsEmpty': 'It looks like you don\'t have any booking requests at the moment.',
    'dashboard.onceReceiveBookingRequests': 'Once you receive booking requests, you can see them here.',
    'dashboard.bookingRequestsCount': 'Booking Requests',
    'dashboard.notSpecified': 'Not specified',
    'dashboard.notProvided': 'Not provided',
    'dashboard.applicationMessage': 'Application Message',
    'dashboard.noMessageProvided': 'No message provided',
    'dashboard.supportingDocument': 'Supporting Document',
    'dashboard.viewDocument': 'View Document',
    'dashboard.noDocumentUploaded': 'No document uploaded',
    'dashboard.requestReceived': 'Request received',
    'dashboard.paymentAuthorizedUntil': 'Payment authorized until',
    'dashboard.acceptApplication': 'Accept Application',
    'dashboard.refuseApplication': 'Refuse Application',
    'dashboard.refuseApplicationConfirm': 'Are you sure you want to refuse this rental application? This action cannot be undone.',
    'dashboard.accepted': 'Accepted',
    'dashboard.refused': 'Refused',
    'dashboard.accountSettings': 'Account Settings',
    'dashboard.fullName': 'Full Name',
    'dashboard.privateLandlord': 'Private Landlord',
    
    // Listing Details
    'listing.backToSearch': 'Back to Search',
    'listing.sendMessage': 'Send Message',
    'listing.messageSent': 'Message Sent',
    'listing.messageSentDesc': 'Your message has been sent to the agency',
    'listing.messageError': 'Failed to send message. Please try again.',
    'listing.loadingDetails': 'Loading listing details...',
    'listing.notFound': 'Listing not found',
    'listing.authRequired': 'Authentication Required',
    'listing.authRequiredDesc': 'Please log in to send a message',
    'listing.messageRequired': 'Message Required',
    'listing.messageRequiredDesc': 'Please enter a message',
    'listing.agencyContact': 'Agency Contact',
    'listing.location': 'Location',
    'listing.amenities': 'Amenities',
    'listing.description': 'Description',
    'listing.perMonth': 'per month',
    'listing.deposit': 'deposit',
    'listing.agencyFee': 'Agency Fee',
    'listing.availableFrom': 'Available from',
    'listing.furnished': 'Furnished',
    'listing.billsIncluded': 'Bills Included',
    'listing.floor': 'Floor',
    'listing.noImages': 'No images available',
    'listing.bedroom': 'bedroom',
    'listing.bedrooms': 'bedrooms',
    'listing.bathroom': 'bathroom',
    'listing.bathrooms': 'bathrooms',
    'listing.inApartment': 'in apartment',
    'listing.mixedGender': 'Mixed gender',
    'listing.only': 'only',
    'listing.paymentApprovalNote': 'If and only after the landlord approves',
    'listing.paymentPlatformNote': "You'll pay through our platform:",
    'listing.requiredDocuments': 'Required Documents',
    'listing.validId': 'Valid ID or Passport',
    'listing.studentCertificate': 'Student enrollment certificate or job offer certificate',
    'listing.optionalHigherChance': '(optional but higher chance to get your booking accepted)',
    'listing.houseRules': 'House Rules',
    'listing.cancellationPolicy': 'Cancellation policy',
    'listing.refundPolicy': 'Your 1st rent will be 100% refunded if you cancel up to 60 days before the contract start date or you\'ll get a 50% refund if you cancel up to 30 days.',
    'listing.fortnightlyContract': 'Fortnightly contract',
    'listing.fortnightlyDescription': 'A fortnightly contract refers to a contract type where you are charged per fortnight booked.',
    'listing.whyRentWithFlat2stdy': 'Why rent with Flat2stdy ?',
    'listing.safeArrival': 'Safe arrival',
    'listing.safeArrivalDescription': 'If your property isn\'t as listed, report it within 24 hours of your move-in. We\'ll freeze your payment and help resolve the issue fast.',
    'listing.stressFreeHousing': 'Stress-free housing',
    'listing.stressFreeDescription': 'Book your stay online effortlessly with Flat2study from anywhere in the world.',
    'listing.fullSupport': 'Full support',
    'listing.fullSupportDescription': 'We\'re here for you every step of the way, from booking through to check-out.',
    'listing.bookingRequestSent': 'Booking request sent!',
    'listing.landlordResponse': 'The landlord will respond within 24 hours.',
    'listing.more': 'more',
    'listing.contract': 'Contract',
    'listing.reviewPriceDetails': 'Review price details',
    'listing.firstRentalPayment': 'First rental payment',
    'listing.halfMonth': '(half month)',
    'listing.oneTimeServiceFee': 'One-time service fee',
    'listing.total': 'Total',
    'listing.availability': 'Availability',
    'listing.available': 'Available',
    'listing.occupied': 'Occupied',
    'listing.availableFromColon': 'Available from:',
    'listing.minStay': 'Min stay:',
    'listing.servicesAndExpenses': 'Services and expenses',
    'listing.securityDeposit': 'Security deposit',
    'listing.securityDepositDesc': 'Refundable payment to be made directly to Landlord, which should be refunded if you meet all the rental conditions with our platform',
    'listing.fixedMonthlyBills': 'Fixed Monthly Bills',
    'listing.water': 'Water',
    'listing.electricity': 'Electricity',
    'listing.internet': 'Internet',
    'listing.gas': 'Gas',
    'listing.includedInPrice': 'Included in the price',
    'listing.notIncludedEst': 'Not included - Est.',
    'listing.perMonthShort': '/month',
    'listing.howToBook': 'How to Book',
    'listing.howToBook.step1.title': 'Find your home 100% online',
    'listing.howToBook.step1.desc': 'With our platform, in-person visits are a thing of the past. Our team verifies the property to offer video tours and photos so you can view them online. We collect all the information you need to make your decision.',
    'listing.howToBook.step2.title': 'Make a booking request',
    'listing.howToBook.step2.desc': "With just a few simple details you can make a request for the property. Remember, we won't charge you until the Landlord confirms.",
    'listing.howToBook.step3.title': 'Get an answer in 24h or less',
    'listing.howToBook.step3.desc': "The Landlord has 24 hours to respond to your booking request. If they accept, your payment method will be charged and we will put you in contact with the Landlord. If they don't accept, no worries, you won't be charged and we'll help you find alternatives.",
    'listing.howToBook.step4.title': 'Move in',
    'listing.howToBook.step4.desc': "Arrange your move-in date, key collection and anything else directly with your Landlord. As an extra security step, we will only transfer the first month's rent to the Landlord 24 hours after you move in, unless you contact us with a problem.",
    'listing.howToBook.remember': 'Remember: you have 24h to check your new home',
    'listing.howToBook.rememberDesc': 'If the property is significantly different to what our listing promised, let us know within 24h since you move in, so we can help you.',
    
    // Property Types
    'propertyType.room': 'Room',
    'propertyType.bedspace': 'Bedspace',
    'propertyType.studio': 'Studio',
    'propertyType.apartment': 'Apartment',
    'propertyType.flat': 'Flat',
    
    // Messages
    'messages.title': 'Messages',
    'messages.loadingMessages': 'Loading messages...',
    'messages.selectConversation': 'Select a conversation',
    'messages.selectConversationDesc': 'Choose a conversation from the list to view messages',
    'messages.manageTenantInquiries': 'Manage inquiries from potential tenants',
    'messages.conversationsWithAgencies': 'Your conversations with property agencies',
    'messages.messageSent': 'Message sent',
    'messages.messageSentDesc': 'Your message has been sent successfully.',
    'messages.messageError': 'Failed to send message. Please try again.',
    'messages.typeReply': 'Type your reply...',
    'messages.typeMessage': 'Type your message...',
    'messages.noConversationsYet': 'No conversations yet',
    'messages.noConversationsDesc': 'When students send inquiries about your listings, they\'ll appear here.',
    'messages.backToHome': 'Back to home',

    // My Listings
    'myListings.title': 'My Listings',
    'myListings.subtitle': 'Manage your property listings',
    'myListings.totalCount': 'total',
    'myListings.addNewListing': 'Add New Listing',
    'myListings.noListingsTitle': 'No listings yet',
    'myListings.noListingsDescription': 'Start by creating your first property listing',
    'myListings.createFirstListing': 'Create Your First Listing',
    'myListings.loadingListings': 'Loading your listings...',
    'myListings.perMonth': 'per month',
    'myListings.actions.view': 'View',
    'myListings.actions.edit': 'Edit',
    'myListings.actions.delete': 'Delete',
    'myListings.deleteConfirm': 'Are you sure you want to delete this listing?',
    'myListings.deleteSuccess': 'Listing deleted successfully',
    'myListings.deleteError': 'Failed to delete listing',
    'myListings.loadError': 'Failed to load your listings',
    'myListings.status.published': 'Published',
    'myListings.status.draft': 'Draft',
    'myListings.status.expired': 'Expired',
    'myListings.status.archived': 'Archived',

    // Favorites
    'favorites.title': 'My Favorites',
    'favorites.backToSearch': 'Back to Search',
    'favorites.savedListings': 'Your saved listings',
    'favorites.loadingFavorites': 'Loading your favorites...',
    'favorites.noFavoritesYet': 'No favorites yet',
    'favorites.noFavoritesDesc': 'Start browsing listings and save the ones you like by clicking the heart icon.',
    'favorites.browseListings': 'Browse Listings',
    'favorites.listingSaved': 'listing',
    'favorites.listingsSaved': 'listings',
    'favorites.saved': 'saved',
    
    // Create Listing
    'createListing.title': 'Create New Listing',
    'createListing.subtitle': 'Add a new property to your portfolio',
    'createListing.back': 'Back',
    'createListing.basicInfo': 'Basic Information',
    'createListing.propertyTitle': 'Property Title',
    'createListing.titlePlaceholder': 'e.g. Cozy Studio near University',
    'createListing.propertyType': 'Property Type',
    'createListing.entireProperty': 'Entire Property',
    'createListing.studio': 'Studio',
    'createListing.roomShared': 'Room in a Shared Property',
    'createListing.bedspaceShared': 'Bedspace in a Shared Room',
    'createListing.numberOfBedrooms': 'Number of Bedrooms',
    'createListing.numberOfBathrooms': 'Number of Bathrooms',
    'createListing.totalBedroomsInApartment': 'Total Bedrooms in Apartment',
    'createListing.totalBathroomsInApartment': 'Total Bathrooms in Apartment',
    'createListing.housematesGender': 'Housemates Gender',
    'createListing.selectHousematesGender': 'Select housemates gender preference',
    'createListing.maleOnly': 'Male only',
    'createListing.femaleOnly': 'Female only',
    'createListing.mixed': 'Mixed',
    'createListing.fullPropertySize': 'Full Property Size (sqm)',
    'createListing.enterSizeSquareMeters': 'Enter size in square meters',
    'createListing.propertyDescription': 'Property Description',
    'createListing.propertyDescriptionPlaceholder': 'Describe your property, its location, nearby amenities, transportation links, and what makes it special...',
    'createListing.minimumCharacters': 'Minimum 50 characters',
    'createListing.selectAmenitiesText': 'Select all amenities available in your property',
    'createListing.houseRules': 'House Rules',
    'createListing.selectRulesText': 'Select the rules that apply to your property',
    'createListing.noSmoking': 'No Smoking',
    'createListing.noPets': 'No Pets',
    // Pricing & Availability Step
    'createListing.rentAmount': 'Rent Amount (EUR) - Per Month',
    'createListing.enterRentAmount': 'Enter rent amount',
    'createListing.securityDeposit': 'Security Deposit',
    'createListing.selectDepositAmount': 'Select deposit amount',
    'createListing.noDepositRequired': 'No deposit required',
    'createListing.oneMonthRent': '1 month rent',
    'createListing.oneAndHalfMonthsRent': '1.5 months rent',
    'createListing.twoMonthsRent': '2 months rent',
    'createListing.threeMonthsRent': '3 months rent',
    'createListing.depositBonus': 'Properties without security deposit have +30% more bookings on average.',
    'createListing.landlordAdminFee': 'Landlord Admin Fee (EUR) - Optional',
    'createListing.enterAdminFee': 'Enter admin fee amount',
    'createListing.adminFeeDescription': 'Optional one-time fee charged to tenants (e.g., application processing fee)',
    'createListing.minimumStay': 'Minimum Stay (months)',
    'createListing.maximumStay': 'Maximum Stay (months)',
    'createListing.minimumStayPlaceholder': 'e.g., 1',
    'createListing.maximumStayPlaceholder': 'Leave empty for no limit',
    'createListing.maximumStayDescription': 'Leave empty for no maximum stay limit',
    'createListing.availableFrom': 'Available From',
    // Utility Costs Step
    'createListing.utilityCosts': 'Utility Costs',
    'createListing.utilityCostsDescription': 'Specify whether utilities are included in the rent or provide estimated monthly costs.',
    'createListing.electricity': 'Electricity',
    'createListing.gas': 'Gas',
    'createListing.water': 'Water',
    'createListing.internet': 'Internet',
    'createListing.included': 'Included in rent',
    'createListing.estimate': 'Estimate monthly cost',
    'createListing.estimatedCost': 'Estimated cost (EUR/month)',
    'createListing.enterEstimatedCost': 'Enter estimated monthly cost',
    // Photos Step
    'createListing.propertyPhotos': 'Property Photos',
    'createListing.photosDescription': 'Upload high-quality photos of your property. Minimum 4 photos required.',
    'createListing.uploadPhotos': 'Upload Photos',
    'createListing.authRequired': 'Authentication required',
    'createListing.signInToUpload': 'Please sign in to upload photos.',
    'createListing.uploadingPhotos': 'Uploading photos...',
    'createListing.uploadSuccess': 'Photo uploaded successfully',
    'createListing.uploadError': 'Failed to upload photo',
    'createListing.removePhoto': 'Remove photo',
    'createListing.photosRequirement': 'You need at least 4 photos to continue.',
    // Review Step
    'createListing.reviewListing': 'Review Your Listing',
    'createListing.reviewDescription': 'Please review all information before submitting your listing for approval.',
    'createListing.basicInformation': 'Basic Information',
    'createListing.propertyInformation': 'Property Information',
    'createListing.pricingInformation': 'Pricing Information',
    'createListing.utilitiesInformation': 'Utilities Information',
    'createListing.includedUtilities': 'Included utilities',
    'createListing.estimatedUtilities': 'Estimated utilities',
    'createListing.submitForReview': 'Submit for Review',
    'createListing.pendingReview': 'Pending Review',
    'createListing.reviewNote': 'Your listing will be reviewed by our team before going live.',
    'createListing.selectType': 'Select type',
    'createListing.description': 'Description',
    'createListing.descriptionPlaceholder': 'Describe your property, its features, and what makes it special...',
    'createListing.propertyImages': 'Property Images',
    'createListing.uploadImages': 'Upload Images',
    'createListing.location': 'Location',
    'createListing.address': 'Address',
    'createListing.addressPlaceholder': 'e.g. Via Roma 123',
    'createListing.city': 'City',
    'createListing.cityPlaceholder': 'e.g. Milan',
    'createListing.country': 'Country',
    'createListing.countryPlaceholder': 'e.g. Italy',
    'createListing.pricingDetails': 'Pricing & Details',
    'createListing.monthlyRent': 'Monthly Rent (EUR)',
    'createListing.deposit': 'Deposit (EUR)',
    'createListing.bedrooms': 'Bedrooms',
    'createListing.bathrooms': 'Bathrooms',
    'createListing.floor': 'Floor',
    'createListing.floorPlaceholder': 'e.g. 2nd floor',
    'createListing.size': 'Size (sqm)',
    'createListing.agencyFee': 'Agency Fee',
    'createListing.agencyFeePlaceholder': 'e.g. One month rent or percentage',
    'createListing.furnished': 'Furnished',
    'createListing.billsIncluded': 'Bills Included',
    'createListing.create': 'Create Listing',
    'createListing.cancel': 'Cancel',
    'createListing.creating': 'Creating...',
    'createListing.step': 'Step',
    'createListing.of': 'of',
    'createListing.complete': 'Complete',
    'createListing.next': 'Next',
    'createListing.propertyDetails': 'Property Details',
    'createListing.amenitiesRules': 'Amenities & Rules',
    'createListing.pricingAvailability': 'Pricing & Availability',
    'createListing.photos': 'Photos',
    'createListing.review': 'Review',
    'createListing.submittedForReview': 'Listing Submitted for Review',
    'createListing.submittedDescription': 'Your listing has been submitted to our admin team for review. You\'ll be notified once it\'s approved and published.',
    'createListing.errorDescription': 'Failed to submit listing. Please try again.',
    'createListing.missingInfo': 'Missing Information',
    'createListing.pleaseProvideRequired': 'Please provide all required information',
    'createListing.error': 'Error',
    'createListing.success': 'Success',
    'createListing.listingCreated': 'Listing created successfully!',
    'createListing.propertyAddress': 'Property Address',
    'createListing.propertyAddressPlaceholder': 'Enter the full address',
    'createListing.addressLine2': 'Address Line 2 (Optional)',
    'createListing.addressLine2Placeholder': 'Apartment, suite, unit, building, floor, etc.',
    'createListing.postcode': 'Postcode',
    'createListing.postcodePlaceholder': 'Enter postcode',
    'createListing.isFurnished': 'Is the property furnished?',
    'createListing.yes': 'Yes',
    'createListing.no': 'No',
    'createListing.furnishedRequired': 'Only furnished properties can be listed on our platform. Please ensure your property is furnished before proceeding.',
    
    // Photos
    'photos.propertyPhotos': 'Property Photos',
    'photos.uploadDescription': 'Upload at least 4 high-quality photos of your property. Include photos of each room, the exterior, and any special features.',
    'photos.choosePhotos': 'Choose Photos',
    'photos.uploading': 'Uploading...',
    'photos.formatSupport': 'Select multiple photos at once. Supported formats: JPG, PNG, WebP',
    'photos.uploadedPhotos': 'Uploaded Photos',
    'photos.minimum': 'minimum',
    'photos.minimumMet': 'Minimum requirement met',
    'photos.moreNeeded': 'more needed',
    'photos.propertyPhoto': 'Property photo',
    'photos.mainPhoto': 'Main Photo',
    'photos.authRequired': 'Authentication required',
    'photos.signInToUpload': 'Please sign in to upload photos.',
    'photos.uploadSuccess': 'Photos uploaded successfully',
    'photos.photosAdded': 'photo(s) added to your listing.',
    'photos.uploadFailed': 'Upload failed',
    'photos.uploadFailedDesc': 'Failed to upload photos. Please try again.',
    
    // Review
    'review.reviewYourListing': 'Review Your Listing',
    'review.reviewDescription': 'Please review all information before submitting your listing for approval.',
    'review.propertyLocation': 'Property Location',
    'review.address': 'Address',
    'review.addressLine2': 'Address Line 2',
    'review.postcode': 'Postcode',
    'review.furnished': 'Furnished',
    'review.unfurnished': 'Unfurnished',
    'review.propertyDetails': 'Property Details',
    'review.type': 'Type',
    'review.size': 'Size',
    'review.bathrooms': 'Bathrooms',
    'review.bedrooms': 'Bedrooms',
    'review.totalBedrooms': 'Total Bedrooms',
    'review.housemates': 'Housemates',
    'review.pricingTerms': 'Pricing & Terms',
    'review.rent': 'Rent',
    'review.deposit': 'Deposit',
    'review.minimumStay': 'Minimum Stay',
    'review.maximumStay': 'Maximum Stay',
    'review.months': 'month(s)',
    'review.availableFrom': 'Available From',
    'review.utilities': 'Utilities',
    'review.includedInRent': 'Included in rent',
    'review.estimatedMonthlyCosts': 'Estimated monthly costs',
    'review.amenitiesRules': 'Amenities & Rules',
    'review.description': 'Description',
    'review.amenities': 'Amenities',
    'review.houseRules': 'House Rules',
    'review.photos': 'Photos',
    'review.propertyPhoto': 'Property photo',
    'review.more': 'more',
    'review.readyToSubmit': 'Ready to Submit',
    'review.submissionInfo': 'During the next 24 hours, our Trust & Safety department will review your listing. If everything is correct, it will appear on the website automatically.',
    'review.submitForReview': 'Submit for Review',
    'review.noDepositRequired': 'No deposit required',
    'review.monthsRent': 'month(s) rent',
    'review.every2Weeks': 'every 2 weeks',
    'review.perDay': 'per day',
    'review.perMonth': 'per month',
    'review.electricity': 'Electricity',
    'review.gas': 'Gas',
    'review.water': 'Water',
    'review.internet': 'Internet',

    // Amenities
    'amenities.wifi': 'WiFi',
    'amenities.kitchen': 'Kitchen',
    'amenities.washingMachine': 'Washing Machine',
    'amenities.dryer': 'Dryer',
    'amenities.dishwasher': 'Dishwasher',
    'amenities.airConditioning': 'Air Conditioning',
    'amenities.heating': 'Heating',
    'amenities.balcony': 'Balcony',
    'amenities.terrace': 'Terrace',
    'amenities.garden': 'Garden',
    'amenities.parking': 'Parking',
    'amenities.elevator': 'Elevator',
    'amenities.swimmingPool': 'Swimming Pool',
    'amenities.gym': 'Gym',
    'amenities.concierge': 'Concierge',
    'amenities.security': 'Security',
    'amenities.tv': 'TV',
    'amenities.desk': 'Desk',
    'amenities.wardrobe': 'Wardrobe',
    
    // Filters
    'filters.price': 'Price',
    'filters.priceRange': 'Price Range (Monthly)',
    'filters.type': 'Type',
    'filters.propertyType': 'Property Type',
    'filters.availableFrom': 'Available From',
    'filters.nearUniversity': 'Near University',
    'filters.university': 'University',
    'filters.selectUniversity': 'Select university',
    'filters.anyUniversity': 'Any university',
    'filters.bedrooms': 'Bedrooms',
    'filters.any': 'Any',
    'filters.bedroom': 'bedroom',
    'filters.bedroomsPlural': 'bedrooms',
    'filters.bedroomsPlus': '3+ bedrooms',
    'filters.furnished': 'Furnished',
    'filters.amenities': 'Amenities',
    'filters.clearAll': 'Clear all',
    'filters.filters': 'Filters',
    'filters.searchFilters': 'Search Filters',
    'filters.sortBy': 'Sort By',
    'filters.sort': 'Sort',
    'filters.types': 'types',
    'filters.amenitiesCount': 'amenities',
    
    // 404 Page
    'notFound.title': '404',
    'notFound.message': 'Oops! Page not found',
    'notFound.returnHome': 'Return to Home',
    
    // Checkout Cancel
    'checkout.cancelled.title': 'Payment Cancelled',
    'checkout.cancelled.message': 'Your payment was cancelled. No charges have been made to your card.',
    'checkout.cancelled.subtitle': 'You can try again or continue browsing other properties.',
    'checkout.cancelled.tryAgain': 'Try Again',
    'checkout.cancelled.browseProperties': 'Browse Properties',
    
    // Platform Communication
    'platform.communication.compact': 'For your safety, all communications must happen through our platform',
    'platform.communication.policy': 'Platform Communication Policy:',
    'platform.communication.message': 'For your safety and security, all communications between tenants and landlords must happen through our platform. Contact information is protected and blurred for privacy.',
    
    // Landlord Landing Page
    'landlord.hero.badge': 'FLAT2STUDY LANDLORDS',
    'landlord.hero.title1': 'Maximize your profitability with our',
    'landlord.hero.title2': 'medium-term renting',
    'landlord.hero.subtitle': 'Your property always booked, secured and generating constant income with verified international students.',
    'landlord.hero.listWithUs': 'List with us',
    'landlord.hero.logIn': 'Log in',
    'landlord.stats.students': '50,000',
    'landlord.stats.studentsLabel': 'students in our network',
    'landlord.stats.studentsSubLabel': 'looking for an apartment per year',
    'landlord.stats.universities': '5 top Milan universities',
    'landlord.stats.universitiesLabel': '',
    'landlord.stats.universitiesSubLabel': 'in our network',
    'landlord.stats.days': '7 days',
    'landlord.stats.daysLabel': 'is enough for our best listings',
    'landlord.stats.daysSubLabel': 'to be rented',
    'landlord.cta.notUsual': 'NOT YOUR USUAL REAL ESTATE AD',
    'landlord.cta.title': 'Everything you need to maximise your earnings',
    'landlord.cta.subtitle': 'High ad visibility. Qualified tenants. Stress-free renting.',
    'landlord.features.qualityTenants': 'Quality tenants',
    'landlord.features.qualityTenantsDesc': 'Access verified student tenants with guaranteed first payments. You always choose whether to accept or not.',
    'landlord.features.onlineBookings': 'Online viewings and bookings',
    'landlord.features.onlineBookingsDesc': 'Save time with virtual tours and direct online bookings. No more endless property showings.',
    'landlord.features.payOnSuccess': 'We only charge you if you rent out',
    'landlord.features.payOnSuccessDesc': 'Pay only when successful - a small percentage of the total contract value once rented, never before.',
    'landlord.features.personalService': 'Personalised service',
    'landlord.features.personalServiceDesc': 'Get expert support from our multilingual team at your disposal to help you at all times.',
    'landlord.steps.title': 'Three simple steps',
    'landlord.steps.step1.title': 'List your property for free',
    'landlord.steps.step1.desc': 'Create your listing with photos and details. No upfront costs.',
    'landlord.steps.step2.title': 'Accept booking requests',
    'landlord.steps.step2.desc': 'Review verified student applications and choose your ideal tenant.',
    'landlord.steps.step3.title': 'Receive payments',
    'landlord.steps.step3.desc': 'Get secure monthly rent payments directly to your account.',
    'landlord.steps.additionalInfo1': 'You will receive complete information about your potential tenants. Once a request is accepted, the tenant pays the first month rental and the deposit.',
    'landlord.steps.additionalInfo2': 'Within 48 hours of your tenant\'s arrival, we will transfer you the first rental payment minus our service fee.',
    'landlord.finalCta.title': 'Ready to start earning?',
    'landlord.finalCta.subtitle': 'Join thousands of landlords already maximizing their rental income with verified student tenants.',
    'landlord.finalCta.startListing': 'Start listing for free',
  },
  it: {
    // Header
    'header.favorites': 'Preferiti',
    'header.signOut': 'Esci',
    'header.signIn': 'Accedi',
    'header.postListing': 'Pubblica Annuncio',
    'header.getStarted': 'Inizia',
    'header.publishListings': 'Pubblica Annunci',
    'header.myListings': 'I Miei Annunci',
    'header.messages': 'Messaggi',
    'header.about': 'Chi Siamo',
    'header.profile': 'Profilo',
    'header.profileInfo': 'Informazioni Profilo',
    'header.language': 'Lingua',
    'header.hello': 'Ciao',
    'header.logIn': 'Accedi',
    'header.start': 'Inizia',
    'header.account': 'Account',
    'header.landlord': 'Sono un proprietario',
    
    // Languages
    'language.english': 'Inglese',
    'language.italian': 'Italiano',
    
    // About Page
    'about.title': 'Chi Siamo',
    'about.backHome': 'Torna alla Home',
    'about.intro1': 'Stanchi della bassa qualità dei servizi immobiliari a Milano, abbiamo deciso di costruire una piattaforma per rendere più sicuro e facile per gli studenti che si trasferiscono all\'Università trovare un posto dove vivere.',
    'about.intro2': 'Selezioniamo attentamente le società immobiliari e i proprietari di case che condividono i loro annunci su questa piattaforma basandoci su vari criteri: rapporto qualità-prezzo, reattività, comfort, al fine di ridurre il più possibile lo stress degli studenti. Ci assicuriamo anche che solo gli studenti possano effettuare acquisti su questa piattaforma per proteggere i proprietari. Godetevi il sito web e buona fortuna nel trovare la vostra casa perfetta!',
    'about.founders': 'Melchior e Teo',
    'about.contactInfo': 'Informazioni di Contatto',
    'about.email': 'Email:',
    'about.partnerTitle': 'Vuoi collaborare con noi?',
    'about.partnerText': 'Scrivi a',
    'about.partnerOr': 'o programma un incontro subito',
    'about.scheduleMeeting': 'Programma Incontro',
    
    // Homepage
    'home.heroWelcome': 'Bentornato',
    'home.heroTitle': 'La tua casa studentesca perfetta, ora e qui!',
    'home.heroSubtitle': 'Colleghiamo gli studenti a alloggi verificati vicino all\'Università Bocconi e alle altre principali università di Milano. Scelto dalle agenzie, amato dagli studenti.',
    'home.heroSubtitleStudent': 'Pronto a trovare il tuo alloggio perfetto per studenti?',
    'home.heroSubtitleRealtor': 'Gestisci i tuoi annunci immobiliari e la tua attività con efficacia.',
    'home.findPlace': 'Trova un Alloggio',
    'home.goToMyListings': 'Vai ai miei annunci',
    'home.universitiesTitle': 'Ideale per studenti delle università d\'eccellenza.',
    'home.universitiesSubtitle': 'Trova alloggi a distanza pedonale o con facile collegamento alle migliori università di Milano',
    'home.featuredTitle': 'Proprietà in Evidenza',
    'home.featuredSubtitle': 'Alloggi selezionati da agenzie di fiducia',
    'home.featured': 'In Evidenza',
    'home.month': '/mese',
    'home.viewDetails': 'Vedi Dettagli',
    'home.viewAll': 'Vedi Tutte le Proprietà',
    'home.quickActions': 'Azioni Rapide',
    'home.quickActionsSubtitle': 'Accedi alle tue funzioni più importanti',
    'home.messages': 'Messaggi',
    'home.messagesDesc': 'Chatta con proprietari e agenzie',
    'home.messagesDescRealtor': 'Chatta con inquilini potenziali',
    'home.savedListings': 'Annunci Salvati',
    'home.savedListingsDesc': 'Visualizza le tue proprietà preferite',
    'home.explore': 'Esplora',
    'home.exploreDesc': 'Scopri nuove proprietà',
    'home.addListing': 'Aggiungi Annuncio',
    'home.addListingDesc': 'Crea un nuovo annuncio immobiliare',
    'home.myListings': 'I Miei Annunci',
    'home.myListingsDesc': 'Visualizza e gestisci le tue proprietà',
    'home.analytics': 'Analisi',
    'home.analyticsDesc': 'Visualizza le prestazioni degli annunci',
    'home.recentActivity': 'Attività Recente',
    'home.recentActivityDesc': 'Nessuna attività recente ancora. Inizia a esplorare per vedere la tua attività qui!',
    'home.dashboardStats': 'Statistiche Dashboard',
    'home.dashboardStatsDesc': 'Panoramica delle prestazioni dei tuoi annunci',
    'home.activeListings': 'Annunci Attivi',
    'home.totalViews': 'Visualizzazioni Totali',
    'home.inquiries': 'Richieste',
    'home.needHelp': 'Hai Bisogno di Aiuto?',
    'home.contactUs': 'Contattaci a teodor.cosmovici@studbocconi.it',
    'home.helpDesc': 'Siamo qui per aiutarti con tutto quello di cui hai bisogno. Rispondiamo entro 24 ore o meno.',
    'home.quickActionsRealtorSubtitle': 'Gestisci i tuoi annunci immobiliari e il tuo business',
    
    // Benefits Section
    'home.whyChooseTitle': 'Perché scegliere Flat2Study?',
    'home.whyChooseSubtitle': 'Rendiamo la ricerca di un alloggio per studenti a Milano sicura, semplice e affidabile.',
    'home.verifiedProperties': 'Proprietà Verificate',
    'home.verifiedPropertiesDesc': 'Tutti gli alloggi sono verificati e pubblicati da agenzie e proprietari di fiducia.',
    'home.studentOnly': 'Solo per Studenti',
    'home.studentOnlyDesc': 'Una piattaforma esclusiva per studenti, che garantisce la migliore esperienza a tutti gli utenti.',
    'home.perfectLocations': 'Posizioni Perfette',
    'home.perfectLocationsDesc': 'Alloggi vicino alle principali università di Milano, con comode opzioni di trasporto.',
    
    'addYourListings': 'Pubblica Il Tuo Annuncio',
    
    // Auth Page
    'auth.backToHome': 'Torna alla Home',
    'auth.title': 'Accedi a Flat2Study',
    'auth.description': 'Accedi al tuo account per gestire i tuoi annunci e messaggi',
    'auth.checkingAuth': 'Verifica autenticazione...',
    'auth.email': 'Email',
    'auth.emailPlaceholder': 'tua.email@esempio.com',
    'auth.password': 'Password',
    'auth.passwordPlaceholder': 'Inserisci la tua password',
    'auth.logIn': 'Accedi',
    'auth.forgotPassword': 'Hai dimenticato la password?',
    'auth.resetTitle': 'Reimposta la tua password',
    'auth.resetDescription': 'Inserisci il tuo indirizzo email e ti invieremo un link per reimpostare la password.',
    'auth.sendResetEmail': 'Invia Email di Reset',
    'auth.backToLogin': 'Torna al login',
    'auth.noAccount': 'Non hai un account?',
    'auth.getStarted': 'Inizia qui',
    'auth.passwordsNoMatch': 'Le password non corrispondono',
    'auth.passwordTooShort': 'La password deve essere lunga almeno 6 caratteri',
    'auth.accountExists': 'Un account con questa email esiste già. Effettua l\'accesso invece.',
    'auth.createFailed': 'Impossibile creare l\'account',
    'auth.accountCreated': 'Account creato con successo! Controlla la tua email per verificare l\'account.',
    'auth.loginFailed': 'Impossibile effettuare l\'accesso',
    'auth.resetFailed': 'Impossibile inviare l\'email di reset',
    'auth.resetSuccess': 'Email di reset password inviata! Controlla la tua casella e segui le istruzioni.',
    
    // User Type Selection
    'userType.backToHome': 'Torna alla Home',
    'userType.title': 'Inizia con Flat2Study',
    'userType.description': 'Scegli il tipo di profilo per creare un account',
    'userType.realtorTitle': 'Per property manager, agenzia immobiliare e azienda',
    'userType.realtorDescription': 'Professionisti del settore immobiliare che gestiscono più proprietà',
    'userType.realtorFeatures': 'Elenca e gestisci proprietà, connettiti con potenziali inquilini, monitora le richieste',
    'userType.privateTitle': 'Per proprietario privato',
    'userType.privateDescription': 'Proprietari individuali che affittano le loro proprietà',
    'userType.privateFeatures': 'Elenca e gestisci proprietà, connettiti con potenziali inquilini, monitora le richieste',
    'userType.studentTitle': 'Per Chi Cerca Casa',
    'userType.studentDescription': 'Studenti alla ricerca di un alloggio',
    'userType.studentFeatures': 'Cerca proprietà, salva i preferiti, richiedi visite, connettiti con i proprietari',
    'userType.getStarted': 'Inizia',
    'userType.alreadyAccount': 'Hai già un account?',
    'userType.logInHere': 'Accedi qui',
    
    // Signup Student
    'signup.student.backToSelection': 'Torna alla Selezione',
    'signup.student.title': 'Registrazione Studente',
    'signup.student.description': 'Crea il tuo account per iniziare a cercare alloggi',
    'signup.student.profilePicture': 'Foto Profilo',
    'signup.student.uploadPhoto': 'Carica Foto',
    'signup.student.name': 'Nome',
    'signup.student.surname': 'Cognome',
    'signup.student.namePlaceholder': 'Nome',
    'signup.student.surnamePlaceholder': 'Cognome',
    'signup.student.phone': 'Numero di Telefono',
    'signup.student.phonePlaceholder': '+39 123 456 7890',
    'signup.student.university': 'Università',
    'signup.student.universityPlaceholder': 'Seleziona la tua università',
    'signup.student.selectUniversity': 'Seleziona la tua università',
    'signup.student.email': 'Email',
    'signup.student.passwordCreate': 'Crea una password (min. 6 caratteri)',
    'signup.student.confirmPassword': 'Conferma Password',
    'signup.student.confirmPasswordPlaceholder': 'Conferma la tua password',
    'signup.student.createAccount': 'Crea Account Studente',
    'signup.student.alreadyHaveAccount': 'Hai già un account?',
    'signup.student.logInHere': 'Accedi qui',
    
    // Signup Realtor
    'signup.realtor.title': 'Registrazione Agente Immobiliare',
    'signup.realtor.description': 'Crea il tuo account professionale per iniziare a pubblicare proprietà',
    'signup.realtor.emailPlaceholder': 'tua.email@azienda.com',
    'signup.realtor.company': 'Azienda',
    'signup.realtor.companyPlaceholder': 'Nome Agenzia Immobiliare',
    'signup.realtor.license': 'Numero Licenza',
    'signup.realtor.licensePlaceholder': 'Numero licenza professionale',
    'signup.realtor.createAccount': 'Crea Account Agente',
    
    // Signup Private
     'signup.private.title': 'Registrazione Proprietario e Property Manager',
     'signup.private.description': 'Crea il tuo account per iniziare a pubblicare la tua proprietà',
     'signup.private.birthDate': 'Data di Nascita',
     'signup.private.codiceFiscale': 'Codice Fiscale',
     'signup.private.codiceFiscalePlaceholder': 'RSSMRA80A01H501Z',
     'signup.private.createAccount': 'Crea Account',
     'signup.private.termsAccept': 'Accetto i',
     'signup.private.termsOfUse': 'Termini di Utilizzo',
     'signup.private.privacyAccept': 'Accetto l\'',
     'signup.private.privacyPolicy': 'Informativa sulla Privacy',
     'signup.private.required': '*',
     'signup.private.termsError': 'Devi accettare i Termini di Utilizzo per continuare',
     'signup.private.privacyError': 'Devi accettare l\'Informativa sulla Privacy per continuare',
    
    // Universities
    'university.bocconi': 'Università Bocconi',
    'university.politecnico': 'Politecnico di Milano',
    'university.cattolica': 'Università Cattolica del Sacro Cuore',
    'university.statale': 'Università Statale',
    'university.other': 'Altra Università',
    
    // Search Page
    'search.placeholder': 'Cerca per posizione, università o servizi...',
    'search.sortBy': 'Ordina per:',
    'search.relevance': 'Rilevanza',
    'search.priceLowHigh': 'Prezzo: Dal Basso all\'Alto',
    'search.priceHighLow': 'Prezzo: Dall\'Alto al Basso',
    'search.newest': 'Più Recenti Prima',
    'search.distance': 'Distanza',
    'search.loading': 'Caricamento annunci...',
    'search.propertiesInView': 'proprietà nella vista corrente',
    'search.noPropertiesView': 'Nessuna proprietà nella vista corrente.',
    'search.moveMap': 'Sposta la mappa per vedere annunci in aree diverse',
    'search.noResults': 'Nessuna proprietà corrisponde ai tuoi criteri di ricerca.',
    'search.clearFilters': 'Cancella Filtri',
    
    // Profile Page
    'profile.back': 'Indietro',
    'profile.about': 'Informazioni',
    'profile.agency': 'Agenzia',
    'profile.student': 'Studente',
    'profile.tellAbout': 'Raccontaci di te...',
    'profile.characters': 'caratteri',
    'profile.cancel': 'Annulla',
    'profile.save': 'Salva',
    'profile.saving': 'Salvando...',
    'profile.noDescription': 'Non hai ancora aggiunto una descrizione. Clicca su modifica per scriverne una.',
    'profile.contact': 'Contatta',
    'profile.contactInformation': 'Informazioni di Contatto',
    'profile.memberSince': 'Membro dal',
    'profile.pleaseSignIn': 'Effettua l\'accesso per visualizzare il tuo profilo.',
    
    // Common
    'common.email': 'Email',
    'common.phone': 'Telefono',
    'common.address': 'Indirizzo',
    'common.city': 'Città',
    'common.country': 'Paese',
    'common.price': 'Prezzo',
    'common.bedrooms': 'Camere da Letto',
    'common.bathrooms': 'Bagni',
    'common.furnished': 'Arredato',
    'common.available': 'Disponibile',
    'common.contact': 'Contatta',
    'common.viewDetails': 'Vedi Dettagli',
    'common.loading': 'Caricamento...',
    'common.error': 'Errore',
    'common.success': 'Successo',
    'common.back': 'Indietro',
    'common.send': 'Invia',
    'common.sending': 'Invio...',
    'common.select': 'Seleziona',
    'common.cancel': 'Annulla',
    'common.save': 'Salva',
    'common.delete': 'Elimina',
    'common.edit': 'Modifica',
    'common.create': 'Crea',
    'common.update': 'Aggiorna',
    'common.view': 'Visualizza',

    // Landlord Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.addListing': 'Aggiungi annuncio',
    'dashboard.addAListing': 'Aggiungi un annuncio',
    'dashboard.backToHome': 'Torna alla Home',
    'dashboard.logout': 'Esci',
    'dashboard.listings': 'Annunci',
    'dashboard.bookingRequests': 'Richieste di prenotazione',
    'dashboard.confirmedBookings': 'Prenotazioni confermate',
    'dashboard.account': 'Account',
    'dashboard.loadingDashboard': 'Caricamento dashboard...',
    'dashboard.quickFind': 'Ricerca veloce',
    'dashboard.addressReference': 'INDIRIZZO / RIFERIMENTO',
    'dashboard.price': 'PREZZO',
    'dashboard.verification': 'VERIFICA',
    'dashboard.tenantsInterested': 'INQUILINI INTERESSATI',
    'dashboard.actions': 'AZIONI',
    'dashboard.bed': 'letto',
    'dashboard.bath': 'bagno',
    'dashboard.ref': 'RIF',
    'dashboard.bedroom': 'Camera',
    'dashboard.requests': 'richieste',
    'dashboard.rented': 'Affittato',
    'dashboard.published': 'Pubblicato',
    'dashboard.rejected': 'Rifiutato',
    'dashboard.pending': 'In sospeso',
    'dashboard.deleteListing': 'Elimina Annuncio',
    'dashboard.deleteListingConfirm': 'Sei sicuro di voler eliminare questo annuncio? Questa azione non può essere annullata.',
    'dashboard.cancel': 'Annulla',
    'dashboard.delete': 'Elimina',
    'dashboard.success': 'Successo',
    'dashboard.listingDeleted': 'Annuncio eliminato con successo',
    'dashboard.error': 'Errore',
    'dashboard.deleteListingError': 'Impossibile eliminare l\'annuncio',
    'dashboard.listingMarkedRented': 'Annuncio contrassegnato come affittato con successo',
    'dashboard.updateListingError': 'Impossibile aggiornare lo stato dell\'annuncio',
    'dashboard.noListingsYet': 'Nessun annuncio ancora',
    'dashboard.createFirstListing': 'Crea il tuo primo annuncio per iniziare a ricevere richieste di prenotazione.',
    'dashboard.getStarted': 'Inizia',
    'dashboard.noBookingRequests': 'Nessuna richiesta di prenotazione',
    'dashboard.noBookingRequestsDesc': 'Quando gli studenti richiederanno di prenotare le tue proprietà, appariranno qui.',
    'dashboard.noConfirmedBookings': 'Nessuna prenotazione confermata',
    'dashboard.noConfirmedBookingsDesc': 'Le prenotazioni confermate appariranno qui.',
    'dashboard.profileInfo': 'Informazioni Profilo',
    'dashboard.editProfile': 'Modifica Profilo',
    'dashboard.signedInAs': 'Sei connesso come',
    'dashboard.checkIn': 'Check-in',
    'dashboard.checkOut': 'Check-out',
    'dashboard.monthlyRent': 'Affitto mensile',
    'dashboard.totalAmountRequested': 'Importo totale richiesto',
    'dashboard.tenant': 'Inquilino',
    'dashboard.university': 'Università',
    'dashboard.createdAt': 'Creato il',
    'dashboard.approve': 'Approva',
    'dashboard.decline': 'Rifiuta',
    'dashboard.bookingApproved': 'Richiesta di prenotazione approvata con successo',
    'dashboard.bookingDeclined': 'Richiesta di prenotazione rifiutata con successo',
    'dashboard.bookingUpdateError': 'Impossibile aggiornare la richiesta di prenotazione',
    'dashboard.noListingsEmpty': 'Nessun annuncio ancora',
    'dashboard.createFirstListingDesc': 'Crea il tuo primo annuncio immobiliare per iniziare ad attirare inquilini.',
    'dashboard.createYourFirstListing': 'Crea il Tuo Primo Annuncio',
    'dashboard.noBookingRequestsEmpty': 'Sembra che tu non abbia richieste di prenotazione al momento.',
    'dashboard.onceReceiveBookingRequests': 'Una volta che riceverai richieste di prenotazione, potrai vederle qui.',
    'dashboard.bookingRequestsCount': 'Richieste di Prenotazione',
    'dashboard.notSpecified': 'Non specificato',
    'dashboard.notProvided': 'Non fornito',
    'dashboard.applicationMessage': 'Messaggio di Candidatura',
    'dashboard.noMessageProvided': 'Nessun messaggio fornito',
    'dashboard.supportingDocument': 'Documento di Supporto',
    'dashboard.viewDocument': 'Visualizza Documento',
    'dashboard.noDocumentUploaded': 'Nessun documento caricato',
    'dashboard.requestReceived': 'Richiesta ricevuta',
    'dashboard.paymentAuthorizedUntil': 'Pagamento autorizzato fino al',
    'dashboard.acceptApplication': 'Accetta Candidatura',
    'dashboard.refuseApplication': 'Rifiuta Candidatura',
    'dashboard.refuseApplicationConfirm': 'Sei sicuro di voler rifiutare questa candidatura di affitto? Questa azione non può essere annullata.',
    'dashboard.accepted': 'Accettato',
    'dashboard.refused': 'Rifiutato',
    'dashboard.accountSettings': 'Impostazioni Account',
    'dashboard.fullName': 'Nome Completo',
    'dashboard.privateLandlord': 'Proprietario Privato',
    
    // Listing Details
    'listing.backToSearch': 'Torna alla Ricerca',
    'listing.sendMessage': 'Invia Messaggio',
    'listing.messageSent': 'Messaggio Inviato',
    'listing.messageSentDesc': 'Il tuo messaggio è stato inviato all\'agenzia',
    'listing.messageError': 'Impossibile inviare il messaggio. Riprova.',
    'listing.loadingDetails': 'Caricamento dettagli annuncio...',
    'listing.notFound': 'Annuncio non trovato',
    'listing.authRequired': 'Autenticazione Richiesta',
    'listing.authRequiredDesc': 'Effettua l\'accesso per inviare un messaggio',
    'listing.messageRequired': 'Messaggio Richiesto',
    'listing.messageRequiredDesc': 'Inserisci un messaggio',
    'listing.agencyContact': 'Contatto Agenzia',
    'listing.location': 'Posizione',
    'listing.amenities': 'Servizi',
    'listing.description': 'Descrizione',
    'listing.perMonth': 'al mese',
    'listing.deposit': 'deposito',
    'listing.agencyFee': 'Commissione Agenzia',
    'listing.availableFrom': 'Disponibile dal',
    'listing.furnished': 'Arredato',
    'listing.billsIncluded': 'Bollette Incluse',
    'listing.floor': 'Piano',
    'listing.noImages': 'Nessuna immagine disponibile',
    'listing.bedroom': 'camera da letto',
    'listing.bedrooms': 'camere da letto',
    'listing.bathroom': 'bagno',
    'listing.bathrooms': 'bagni',
    'listing.inApartment': "nell'appartamento",
    'listing.mixedGender': 'Genere misto',
    'listing.only': 'solo',
    'listing.paymentApprovalNote': 'Se e solo dopo che il proprietario approva',
    'listing.paymentPlatformNote': 'Pagherai tramite la nostra piattaforma:',
    'listing.requiredDocuments': 'Documenti Richiesti',
    'listing.validId': 'Documento d\'identità o Passaporto valido',
    'listing.studentCertificate': 'Certificato di iscrizione universitaria o offerta di lavoro',
    'listing.optionalHigherChance': '(opzionale ma maggiori possibilità di accettazione)',
    'listing.houseRules': 'Regole della Casa',
    'listing.cancellationPolicy': 'Politica di cancellazione',
    'listing.refundPolicy': 'Il tuo primo affitto sarà rimborsato al 100% se cancelli fino a 60 giorni prima della data di inizio contratto o riceverai un rimborso del 50% se cancelli fino a 30 giorni.',
    'listing.fortnightlyContract': 'Contratto quindicinale',
    'listing.fortnightlyDescription': 'Un contratto quindicinale si riferisce a un tipo di contratto dove si viene addebitati per quindicina prenotata.',
    'listing.whyRentWithFlat2stdy': 'Perché affittare con Flat2stdy ?',
    'listing.safeArrival': 'Arrivo sicuro',
    'listing.safeArrivalDescription': 'Se la tua proprietà non è come indicato, segnalalo entro 24 ore dal trasloco. Bloccheremo il pagamento e aiuteremo a risolvere il problema velocemente.',
    'listing.stressFreeHousing': 'Alloggio senza stress',
    'listing.stressFreeDescription': 'Prenota il tuo soggiorno online senza sforzo con Flat2study da qualsiasi parte del mondo.',
    'listing.fullSupport': 'Supporto completo',
    'listing.fullSupportDescription': 'Siamo qui per te in ogni fase, dalla prenotazione al check-out.',
    'listing.bookingRequestSent': 'Richiesta di prenotazione inviata!',
    'listing.landlordResponse': 'Il proprietario risponderà entro 24 ore.',
    'listing.more': 'altro',
    'listing.contract': 'Contratto',
    'listing.reviewPriceDetails': 'Controlla i dettagli del prezzo',
    'listing.firstRentalPayment': 'Primo pagamento affitto',
    'listing.halfMonth': '(metà mese)',
    'listing.oneTimeServiceFee': 'Commissione di servizio una tantum',
    'listing.total': 'Totale',
    'listing.availability': 'Disponibilità',
    'listing.available': 'Disponibile',
    'listing.occupied': 'Occupato',
    'listing.availableFromColon': 'Disponibile dal:',
    'listing.minStay': 'Soggiorno minimo:',
    'listing.servicesAndExpenses': 'Servizi e spese',
    'listing.securityDeposit': 'Deposito cauzionale',
    'listing.securityDepositDesc': 'Pagamento rimborsabile da effettuare direttamente al proprietario, che dovrebbe essere restituito se rispetti tutte le condizioni di locazione con la nostra piattaforma',
    'listing.fixedMonthlyBills': 'Bollette Mensili Fisse',
    'listing.water': 'Acqua',
    'listing.electricity': 'Elettricità',
    'listing.internet': 'Internet',
    'listing.gas': 'Gas',
    'listing.includedInPrice': 'Incluso nel prezzo',
    'listing.notIncludedEst': 'Non incluso - Stima',
    'listing.perMonthShort': '/mese',
    'listing.howToBook': 'Come Prenotare',
    'listing.howToBook.step1.title': 'Trova la tua casa 100% online',
    'listing.howToBook.step1.desc': 'Con la nostra piattaforma, le visite di persona sono un ricordo del passato. Il nostro team verifica la proprietà per offrire video tour e foto in modo che tu possa visionarli online. Raccogliamo tutte le informazioni di cui hai bisogno per prendere la tua decisione.',
    'listing.howToBook.step2.title': 'Fai una richiesta di prenotazione',
    'listing.howToBook.step2.desc': 'Con pochi semplici dettagli puoi fare una richiesta per la proprietà. Ricorda, non ti addebiteremo nulla fino a quando il proprietario non confermerà.',
    'listing.howToBook.step3.title': 'Ricevi una risposta in 24 ore o meno',
    'listing.howToBook.step3.desc': 'Il proprietario ha 24 ore per rispondere alla tua richiesta di prenotazione. Se accetta, il tuo metodo di pagamento verrà addebitato e ti metteremo in contatto con il proprietario. Se non accetta, non preoccuparti, non ti sarà addebitato nulla e ti aiuteremo a trovare alternative.',
    'listing.howToBook.step4.title': 'Trasferisciti',
    'listing.howToBook.step4.desc': "Organizza la data del tuo trasloco, il ritiro delle chiavi e qualsiasi altra cosa direttamente con il tuo proprietario. Come ulteriore misura di sicurezza, trasferiremo l'affitto del primo mese al proprietario solo 24 ore dopo il tuo trasloco, a meno che non ci contatti per un problema.",
    'listing.howToBook.remember': 'Ricorda: hai 24 ore per controllare la tua nuova casa',
    'listing.howToBook.rememberDesc': 'Se la proprietà è significativamente diversa da quanto promesso nel nostro annuncio, faccelo sapere entro 24 ore dal trasloco, così possiamo aiutarti.',
    
    // Property Types
    'propertyType.room': 'Camera',
    'propertyType.bedspace': 'Posto Letto',
    'propertyType.studio': 'Monolocale',
    'propertyType.apartment': 'Appartamento',
    'propertyType.flat': 'Appartamento',
    
    // Messages
    'messages.title': 'Messaggi',
    'messages.loadingMessages': 'Caricamento messaggi...',
    'messages.selectConversation': 'Seleziona una conversazione',
    'messages.selectConversationDesc': 'Scegli una conversazione dall\'elenco per visualizzare i messaggi',
    'messages.manageTenantInquiries': 'Gestisci le richieste degli inquilini potenziali',
    'messages.conversationsWithAgencies': 'Le tue conversazioni con le agenzie immobiliari',
    'messages.messageSent': 'Messaggio inviato',
    'messages.messageSentDesc': 'Il tuo messaggio è stato inviato con successo.',
    'messages.messageError': 'Impossibile inviare il messaggio. Riprova.',
    'messages.typeReply': 'Scrivi la tua risposta...',
    'messages.typeMessage': 'Scrivi il tuo messaggio...',
    'messages.noConversationsYet': 'Nessuna conversazione al momento',
    'messages.noConversationsDesc': 'Quando gli studenti invieranno richieste sui tuoi annunci, appariranno qui.',
    'messages.backToHome': 'Torna a casa',
    
    // My Listings
    'myListings.title': 'I Miei Annunci',
    'myListings.subtitle': 'Gestisci i tuoi annunci immobiliari',
    'myListings.totalCount': 'in totale',
    'myListings.addNewListing': 'Aggiungi Nuovo Annuncio',
    'myListings.noListingsTitle': 'Nessun annuncio ancora',
    'myListings.noListingsDescription': 'Inizia creando il tuo primo annuncio immobiliare',
    'myListings.createFirstListing': 'Crea il Tuo Primo Annuncio',
    'myListings.loadingListings': 'Caricamento annunci...',
    'myListings.perMonth': 'al mese',
    'myListings.actions.view': 'Visualizza',
    'myListings.actions.edit': 'Modifica',
    'myListings.actions.delete': 'Elimina',
    'myListings.deleteConfirm': 'Sei sicuro di voler eliminare questo annuncio?',
    'myListings.deleteSuccess': 'Annuncio eliminato con successo',
    'myListings.deleteError': 'Errore nell\'eliminazione dell\'annuncio',
    'myListings.loadError': 'Errore nel caricamento degli annunci',
    'myListings.status.published': 'Pubblicato',
    'myListings.status.draft': 'Bozza',
    'myListings.status.expired': 'Scaduto',
    'myListings.status.archived': 'Archiviato',
    
    // Favorites
    'favorites.title': 'I Miei Preferiti',
    'favorites.backToSearch': 'Torna alla Ricerca',
    'favorites.savedListings': 'I tuoi annunci salvati',
    'favorites.loadingFavorites': 'Caricamento preferiti...',
    'favorites.noFavoritesYet': 'Nessun preferito ancora',
    'favorites.noFavoritesDesc': 'Inizia a sfogliare gli annunci e salva quelli che ti piacciono cliccando l\'icona del cuore.',
    'favorites.browseListings': 'Sfoglia Annunci',
    'favorites.listingSaved': 'annuncio',
    'favorites.listingsSaved': 'annunci',
    'favorites.saved': 'salvati',
    
    // Create Listing
    'createListing.title': 'Crea Nuovo Annuncio',
    'createListing.subtitle': 'Aggiungi una nuova proprietà al tuo portfolio',
    'createListing.basicInfo': 'Informazioni di Base',
    'createListing.propertyTitle': 'Titolo Annuncio',
    'createListing.propertyType': 'Tipologia di Immobile',
    'createListing.entireProperty': 'Intera Proprietà',
    'createListing.studio': 'Monolocale',
    'createListing.roomShared': 'Camera in Proprietà Condivisa',
    'createListing.bedspaceShared': 'Posto Letto',
    'createListing.numberOfBedrooms': 'Numero di Camere da Letto',
    'createListing.numberOfBathrooms': 'Numero di Bagni',
    'createListing.totalBedroomsInApartment': 'Camere da Letto Totali nell\'Appartamento',
    'createListing.totalBathroomsInApartment': 'Bagni Totali nell\'Appartamento',
    'createListing.housematesGender': 'Genere Coinquilini',
    'createListing.selectHousematesGender': 'Seleziona preferenza genere coinquilini',
    'createListing.maleOnly': 'Solo maschi',
    'createListing.femaleOnly': 'Solo femmine',
    'createListing.mixed': 'Misto',
    'createListing.fullPropertySize': 'Dimensione Totale Proprietà (mq)',
    'createListing.enterSizeSquareMeters': 'Inserisci dimensione in metri quadrati',
    'createListing.propertyDescription': 'Descrizione Proprietà',
    'createListing.propertyDescriptionPlaceholder': 'Descrivi la tua proprietà, la sua posizione, i servizi nelle vicinanze, i collegamenti di trasporto e cosa la rende speciale...',
    'createListing.minimumCharacters': 'Minimo 50 caratteri',
    'createListing.selectAmenitiesText': 'Seleziona tutti i servizi disponibili nella tua proprietà',
    'createListing.houseRules': 'Regole della Casa',
    'createListing.selectRulesText': 'Seleziona le regole che si applicano alla tua proprietà',
    'createListing.noSmoking': 'Vietato Fumare',
    'createListing.noPets': 'Animali Non Ammessi',
    // Pricing & Availability Step  
    'createListing.rentAmount': 'Importo Affitto (EUR) - Al Mese',
    'createListing.enterRentAmount': 'Inserisci importo affitto',
    'createListing.securityDeposit': 'Deposito Cauzionale',
    'createListing.selectDepositAmount': 'Seleziona importo deposito',
    'createListing.noDepositRequired': 'Nessun deposito richiesto',
    'createListing.oneMonthRent': '1 mese di affitto',
    'createListing.oneAndHalfMonthsRent': '1,5 mesi di affitto',
    'createListing.twoMonthsRent': '2 mesi di affitto',
    'createListing.threeMonthsRent': '3 mesi di affitto',
    'createListing.depositBonus': 'Le proprietà senza deposito cauzionale hanno +30% di prenotazioni in più in media.',
    'createListing.landlordAdminFee': 'Commissione Amministrativa Proprietario (EUR) - Opzionale',
    'createListing.enterAdminFee': 'Inserisci importo commissione amministrativa',
    'createListing.adminFeeDescription': 'Commissione una tantum opzionale addebitata agli inquilini (es. commissione per elaborazione richiesta)',
    'createListing.minimumStay': 'Soggiorno Minimo (mesi)',
    'createListing.maximumStay': 'Soggiorno Massimo (mesi)',
    'createListing.minimumStayPlaceholder': 'es., 1',
    'createListing.maximumStayPlaceholder': 'Lascia vuoto per nessun limite',
    'createListing.maximumStayDescription': 'Lascia vuoto per nessun limite di soggiorno massimo',
    'createListing.availableFrom': 'Disponibile Dal',
    // Utility Costs Step
    'createListing.utilityCosts': 'Costi Utenze',
    'createListing.utilityCostsDescription': 'Specifica se le utenze sono incluse nell\'affitto o fornisci i costi mensili stimati.',
    'createListing.electricity': 'Elettricità',
    'createListing.gas': 'Gas',
    'createListing.water': 'Acqua',
    'createListing.internet': 'Internet',
    'createListing.included': 'Incluso nell\'affitto',
    'createListing.estimate': 'Stima costo mensile',
    'createListing.estimatedCost': 'Costo stimato (EUR/mese)',
    'createListing.enterEstimatedCost': 'Inserisci costo mensile stimato',
    // Photos Step
    'createListing.propertyPhotos': 'Foto della Proprietà',
    'createListing.photosDescription': 'Carica foto di alta qualità della tua proprietà. Minimo 4 foto richieste.',
    'createListing.uploadPhotos': 'Carica Foto',
    'createListing.authRequired': 'Autenticazione richiesta',
    'createListing.signInToUpload': 'Effettua l\'accesso per caricare le foto.',
    'createListing.uploadingPhotos': 'Caricamento foto...',
    'createListing.uploadSuccess': 'Foto caricata con successo',
    'createListing.uploadError': 'Impossibile caricare la foto',
    'createListing.removePhoto': 'Rimuovi foto',
    'createListing.photosRequirement': 'Ti servono almeno 4 foto per continuare.',
    // Review Step
    'createListing.reviewListing': 'Rivedi il Tuo Annuncio',
    'createListing.reviewDescription': 'Rivedi tutte le informazioni prima di inviare il tuo annuncio per l\'approvazione.',
    'createListing.basicInformation': 'Informazioni di Base',
    'createListing.propertyInformation': 'Informazioni Proprietà',
    'createListing.pricingInformation': 'Informazioni Prezzi',
    'createListing.utilitiesInformation': 'Informazioni Utenze',
    'createListing.includedUtilities': 'Utenze incluse',
    'createListing.estimatedUtilities': 'Utenze stimate',
    'createListing.submitForReview': 'Invia per Revisione',
    'createListing.pendingReview': 'In Attesa di Revisione',
    'createListing.reviewNote': 'Il tuo annuncio sarà esaminato dal nostro team prima di andare online.',
    'createListing.selectType': 'Seleziona tipologia',
    'createListing.description': 'Descrizione',
    'createListing.descriptionPlaceholder': 'Descrivi il tuo immobile...',
    'createListing.propertyImages': 'Immagini della Proprietà',
    'createListing.uploadImages': 'Carica Immagini',
    'createListing.location': 'Posizione',
    'createListing.address': 'Indirizzo',
    'createListing.addressPlaceholder': 'Via / indirizzo',
    'createListing.city': 'Città',
    'createListing.cityPlaceholder': 'Città',
    'createListing.country': 'Paese',
    'createListing.countryPlaceholder': 'Paese',
    'createListing.pricingDetails': 'Prezzo & Dettagli',
    'createListing.monthlyRent': 'Affitto Mensile (EUR)',
    'createListing.deposit': 'Deposito (EUR)',
    'createListing.bedrooms': 'Camere da Letto',
    'createListing.bathrooms': 'Bagni',
    'createListing.floor': 'Piano',
    'createListing.floorPlaceholder': '2°',
    'createListing.size': 'Superficie (mq)',
    'createListing.agencyFee': 'Commissione Agenzia',
    'createListing.agencyFeePlaceholder': 'es. 500 EUR o 1 mese di affitto',
    'createListing.furnished': 'Arredato',
    'createListing.billsIncluded': 'Spese Incluse',
    'createListing.create': 'Crea Annuncio',
    'createListing.creating': 'Creando...',
    'createListing.cancel': 'Annulla',
    'createListing.back': 'Indietro',
    'createListing.step': 'Passo',
    'createListing.of': 'di',
    'createListing.complete': 'Completato',
    'createListing.next': 'Avanti',
    'createListing.propertyDetails': 'Dettagli Proprietà',
    'createListing.amenitiesRules': 'Servizi e Regole',
    'createListing.pricingAvailability': 'Prezzi e Disponibilità',
    'createListing.photos': 'Foto',
    'createListing.review': 'Revisione',
    'createListing.submittedForReview': 'Inviato per Revisione',
    'createListing.submittedDescription': 'Il tuo annuncio è stato inviato al nostro team di amministrazione per la revisione. Sarai avvisato una volta approvato e pubblicato.',
    'createListing.error': 'Errore',
    'createListing.errorDescription': 'Impossibile inviare l\'annuncio. Riprova.',
    'createListing.propertyAddress': 'Indirizzo Proprietà',
    'createListing.propertyAddressPlaceholder': 'Inserisci l\'indirizzo completo',
    'createListing.addressLine2': 'Indirizzo Riga 2 (Opzionale)',
    'createListing.addressLine2Placeholder': 'Appartamento, scala, piano, edificio, ecc.',
    'createListing.postcode': 'Codice Postale',
    'createListing.postcodePlaceholder': 'Inserisci il codice postale',
    'createListing.isFurnished': 'L\'immobile è arredato?',
    'createListing.yes': 'Sì',
    'createListing.no': 'No',
    'createListing.furnishedRequired': 'Solo gli immobili arredati possono essere pubblicati sulla nostra piattaforma. Assicurati che il tuo immobile sia arredato prima di continuare.',
    
    // Photos
    'photos.propertyPhotos': 'Foto dell\'Immobile',
    'photos.uploadDescription': 'Carica almeno 4 foto di alta qualità della tua proprietà. Includi foto di ogni stanza, dell\'esterno e di eventuali caratteristiche speciali.',
    'photos.choosePhotos': 'Scegli Foto',
    'photos.uploading': 'Caricamento...',
    'photos.formatSupport': 'Seleziona più foto contemporaneamente. Formati supportati: JPG, PNG, WebP',
    'photos.uploadedPhotos': 'Foto Caricate',
    'photos.minimum': 'minimo',
    'photos.minimumMet': 'Requisito minimo soddisfatto',
    'photos.moreNeeded': 'ancora necessarie',
    'photos.propertyPhoto': 'Foto proprietà',
    'photos.mainPhoto': 'Foto Principale',
    'photos.authRequired': 'Autenticazione richiesta',
    'photos.signInToUpload': 'Accedi per caricare le foto.',
    'photos.uploadSuccess': 'Foto caricate con successo',
    'photos.photosAdded': 'foto aggiunte al tuo annuncio.',
    'photos.uploadFailed': 'Caricamento fallito',
    'photos.uploadFailedDesc': 'Impossibile caricare le foto. Riprova.',
    
    // Review
    'review.reviewYourListing': 'Revisiona il Tuo Annuncio',
    'review.reviewDescription': 'Rivedi tutte le informazioni prima di inviare il tuo annuncio per approvazione.',
    'review.propertyLocation': 'Posizione Proprietà',
    'review.address': 'Indirizzo',
    'review.addressLine2': 'Indirizzo Riga 2',
    'review.postcode': 'Codice Postale',
    'review.furnished': 'Arredato',
    'review.unfurnished': 'Non Arredato',
    'review.propertyDetails': 'Dettagli Proprietà',
    'review.type': 'Tipo',
    'review.size': 'Dimensione',
    'review.bathrooms': 'Bagni',
    'review.bedrooms': 'Camere da Letto',
    'review.totalBedrooms': 'Totale Camere da Letto',
    'review.totalBathrooms': 'Totale Bagni',
    'review.housemates': 'Coinquilini',
    'review.pricingTerms': 'Prezzi e Condizioni',
    'review.rent': 'Affitto',
    'review.deposit': 'Deposito',
    'review.minimumStay': 'Soggiorno Minimo',
    'review.maximumStay': 'Soggiorno Massimo',
    'review.months': 'mese/i',
    'review.availableFrom': 'Disponibile Dal',
    'review.utilities': 'Utenze',
    'review.includedInRent': 'Incluso nell\'affitto',
    'review.estimatedMonthlyCosts': 'Costi mensili stimati',
    'review.amenitiesRules': 'Servizi e Regole',
    'review.description': 'Descrizione',
    'review.amenities': 'Servizi',
    'review.houseRules': 'Regole della Casa',
    'review.photos': 'Foto',
    'review.propertyPhoto': 'Foto proprietà',
    'review.more': 'altre',
    'review.readyToSubmit': 'Pronto per Inviare',
    'review.submissionInfo': 'Nelle prossime 24 ore, il nostro dipartimento Trust & Safety esaminerà il tuo annuncio. Se tutto è corretto, apparirà automaticamente sul sito web.',
    'review.submitForReview': 'Invia per Revisione',
    'review.noDepositRequired': 'Nessun deposito richiesto',
    'review.monthsRent': 'mese/i di affitto',
    'review.every2Weeks': 'ogni 2 settimane',
    'review.perDay': 'al giorno',
    'review.perMonth': 'al mese',
    'review.electricity': 'Elettricità',
    'review.gas': 'Gas',
    'review.water': 'Acqua',
    'review.internet': 'Internet',

    // Amenities
    'amenities.wifi': 'WiFi',
    'amenities.kitchen': 'Cucina',
    'amenities.washingMachine': 'Lavatrice',
    'amenities.dryer': 'Asciugatrice',
    'amenities.dishwasher': 'Lavastoviglie',
    'amenities.airConditioning': 'Aria Condizionata',
    'amenities.heating': 'Riscaldamento',
    'amenities.balcony': 'Balcone',
    'amenities.terrace': 'Terrazza',
    'amenities.garden': 'Giardino',
    'amenities.parking': 'Parcheggio',
    'amenities.elevator': 'Ascensore',
    'amenities.swimmingPool': 'Piscina',
    'amenities.gym': 'Palestra',
    'amenities.concierge': 'Portineria',
    'amenities.security': 'Sicurezza',
    'amenities.tv': 'TV',
    'amenities.desk': 'Scrivania',
    'amenities.wardrobe': 'Armadio',
    
    // Filters
    'filters.price': 'Prezzo',
    'filters.priceRange': 'Fascia di Prezzo (Mensile)',
    'filters.type': 'Tipo',
    'filters.propertyType': 'Tipo di Proprietà',
    'filters.availableFrom': 'Disponibile Dal',
    'filters.nearUniversity': 'Vicino all\'Università',
    'filters.university': 'Università',
    'filters.selectUniversity': 'Seleziona università',
    'filters.anyUniversity': 'Qualsiasi università',
    'filters.bedrooms': 'Camere da Letto',
    'filters.any': 'Qualsiasi',
    'filters.bedroom': 'camera da letto',
    'filters.bedroomsPlural': 'camere da letto',
    'filters.bedroomsPlus': '3+ camere da letto',
    'filters.furnished': 'Arredato',
    'filters.amenities': 'Servizi',
    'filters.clearAll': 'Cancella tutto',
    'filters.filters': 'Filtri',
    'filters.searchFilters': 'Filtri di Ricerca',
    'filters.sortBy': 'Ordina Per',
    'filters.sort': 'Ordina',
    'filters.types': 'tipi',
    'filters.amenitiesCount': 'servizi',
    
    // 404 Page
    'notFound.title': '404',
    'notFound.message': 'Ops! Pagina non trovata',
    'notFound.returnHome': 'Torna alla Home',
    
    // Checkout Cancel
    'checkout.cancelled.title': 'Pagamento Annullato',
    'checkout.cancelled.message': 'Il tuo pagamento è stato annullato. Non è stato addebitato nulla sulla tua carta.',
    'checkout.cancelled.subtitle': 'Puoi riprovare o continuare a navigare tra le altre proprietà.',
    'checkout.cancelled.tryAgain': 'Riprova',
    'checkout.cancelled.browseProperties': 'Sfoglia Proprietà',
    
    // Platform Communication
    'platform.communication.compact': 'Per la tua sicurezza, tutte le comunicazioni devono avvenire attraverso la nostra piattaforma',
    'platform.communication.policy': 'Politica di Comunicazione della Piattaforma:',
    'platform.communication.message': 'Per la tua sicurezza e protezione, tutte le comunicazioni tra inquilini e proprietari devono avvenire attraverso la nostra piattaforma. Le informazioni di contatto sono protette e sfocate per la privacy.',
    
    // Landlord Landing Page
    'landlord.hero.badge': 'FLAT2STUDY PROPRIETARI',
    'landlord.hero.title1': 'Massimizza la tua redditività con i nostri',
    'landlord.hero.title2': 'affitti a medio termine',
    'landlord.hero.subtitle': 'La tua proprietà sempre prenotata, sicura e che genera reddito costante con studenti internazionali verificati.',
    'landlord.hero.listWithUs': 'Affitta il tuo posto con noi',
    'landlord.hero.logIn': 'Accedi',
    'landlord.stats.students': '50.000',
    'landlord.stats.studentsLabel': 'studenti nella nostra rete',
    'landlord.stats.studentsSubLabel': 'che cercano un appartamento all\'anno',
    'landlord.stats.universities': '5 università top di Milano',
    'landlord.stats.universitiesLabel': '',
    'landlord.stats.universitiesSubLabel': 'nella nostra rete',
    'landlord.stats.days': '7 giorni',
    'landlord.stats.daysLabel': 'bastano per i nostri migliori annunci',
    'landlord.stats.daysSubLabel': 'per essere affittati',
    'landlord.cta.notUsual': 'NON IL SOLITO ANNUNCIO IMMOBILIARE',
    'landlord.cta.title': 'Tutto quello che ti serve per massimizzare i tuoi guadagni',
    'landlord.cta.subtitle': 'Alta visibilità dell\'annuncio. Inquilini qualificati. Affitti senza stress.',
    'landlord.features.qualityTenants': 'Inquilini di qualità',
    'landlord.features.qualityTenantsDesc': 'Accedi a studenti inquilini verificati con pagamenti di primo mese garantiti. Scegli sempre tu se accettare o meno.',
    'landlord.features.onlineBookings': 'Visite online e prenotazioni',
    'landlord.features.onlineBookingsDesc': 'Risparmia tempo con tour virtuali e prenotazioni online dirette. Niente più visite infinite alla proprietà.',
    'landlord.features.payOnSuccess': 'Ti facciamo pagare solo se affitti',
    'landlord.features.payOnSuccessDesc': 'Paghi solo quando hai successo - una piccola percentuale del valore totale del contratto una volta affittato, mai prima.',
    'landlord.features.personalService': 'Servizio personalizzato',
    'landlord.features.personalServiceDesc': 'Ottieni supporto esperto dal nostro team multilingue a tua disposizione per aiutarti in ogni momento.',
    'landlord.steps.title': 'Tre semplici passaggi',
    'landlord.steps.step1.title': 'Elenca la tua proprietà gratuitamente',
    'landlord.steps.step1.desc': 'Crea il tuo annuncio con foto e dettagli. Nessun costo iniziale.',
    'landlord.steps.step2.title': 'Accetta richieste di prenotazione',
    'landlord.steps.step2.desc': 'Esamina le candidature di studenti verificati e scegli il tuo inquilino ideale.',
    'landlord.steps.step3.title': 'Ricevi pagamenti',
    'landlord.steps.step3.desc': 'Ottieni pagamenti mensili dell\'affitto sicuri direttamente sul tuo conto.',
    'landlord.steps.additionalInfo1': 'Riceverai informazioni complete sui tuoi potenziali inquilini. Una volta accettata una richiesta, l\'inquilino paga il primo mese di affitto e il deposito.',
    'landlord.steps.additionalInfo2': 'Entro 48 ore dall\'arrivo del tuo inquilino, ti trasferiremo il primo pagamento dell\'affitto meno la nostra commissione di servizio.',
    'landlord.finalCta.title': 'Pronto a iniziare a guadagnare?',
    'landlord.finalCta.subtitle': 'Unisciti a migliaia di proprietari che stanno già massimizzando il loro reddito da affitto con studenti inquilini verificati.',
    'landlord.finalCta.startListing': 'Inizia a pubblicare gratuitamente',
  }
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  // Initialize language from localStorage immediately to avoid flash of wrong language
  const getInitialLanguage = (): Language => {
    if (typeof window !== 'undefined') {
      const savedLanguage = localStorage.getItem('language') as Language;
      if (savedLanguage && (savedLanguage === 'en' || savedLanguage === 'it')) {
        return savedLanguage;
      }
    }
    return 'en';
  };

  const [language, setLanguageState] = useState<Language>(getInitialLanguage);

  const setLanguage = (newLanguage: Language) => {
    setLanguageState(newLanguage);
    localStorage.setItem('language', newLanguage);
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}